name = "MultivariateInterpolation"
uuid = "3bf71ede-77e0-489f-b05b-7380d1215192"
authors = ["Uwe Hernandez Acosta"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
Combinatorics = "1"
julia = "1.8.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
